language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
install:
  - pip install dbus-python
  - pip install python-systemd
# # command to run tests, e.g. python setup.py test
# # script:  PLEASE CHANGE ME
